services:
  mariadb:
    image: mariadb:11

    container_name: mariadb

    restart: unless-stopped

    command:
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - db:/var/lib/mysql

    networks:
      - nextcloud

  nextcloud:
    container_name: nextcloud

    image: nextcloud:31-fpm

    restart: unless-stopped

    depends_on:
      - mariadb

    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      NEXTCLOUD_DATA: ${NEXTCLOUD_DATA}
      PHP_UPLOAD_LIMIT: 2G

    volumes:
      #/path/to/store/nextcloud/data : var/www/html
      - ${NEXTCLOUD_DATA}:/var/www/html/data
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - nextcloud:/var/www/html

    networks:
      - nextcloud
      - proxy

  nextcloud-cron:
    container_name: nextcloud-cron

    image: nextcloud:31-fpm

    restart: unless-stopped

    depends_on: 
     - mariadb

    entrypoint: /cron.sh

    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      NEXTCLOUD_DATA: ${NEXTCLOUD_DATA}
      PHP_UPLOAD_LIMIT: 2G

    volumes:
      #/path/to/store/nextcloud/data : var/www/html
      - ${NEXTCLOUD_DATA}:/var/www/html/data
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - nextcloud:/var/www/html

    networks:
      - nextcloud

  redis:
    image: redis:8-alpine

    container_name: redis

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis:/data

    networks:
      - nextcloud

volumes:
  db:
  redis:
  nextcloud:
    external: true

networks:
  nextcloud:
    external: true
  proxy:
    external: true